from __future__ import annotations
from typing import Any, Callable, Dict, List, Tuple, Sequence
from enum import Enum
import flame
from PySide6 import QtCore, QtGui, QtWidgets

# Auto-generated enhanced stub from pyflame_lib.py
LIB_PATH: Any
SCRIPT_NAME: Any
SCRIPT_PATH: Any
SHARED_FILE_SEQUENCE_PATH: Any
SHARED_MOVIE_EXPORT_PATH: Any
class Color(Enum):
    BLUE: Any
    RED: Any
    YELLOW: Any
    GREEN: Any
    TEAL: Any
    BLUE_TRANS: Any
    RED_TRANS: Any
    YELLOW_TRANS: Any
    GREEN_TRANS: Any
    TEAL_TRANS: Any
    GRAY: Any
    DARK_GRAY: Any
    BRIGHT_GRAY: Any
    BLACK: Any
    WHITE: Any
    TEXT: Any
    TEXT_BRIGHT: Any
    TEXT_SELECTED: Any
    TEXT_DISABLED: Any
    TEXT_UNDERLINE: Any
    TEXT_BORDER: Any
    TEXT_READ_ONLY_BACKGROUND: Any
    BUTTON_TEXT: Any
    SELECTED_GRAY: Any
    BORDER: Any
    BORDER_BRIGHTER: Any
    UNDERLINE: Any
    ENTRY_GRAY: Any
    DISABLED_GRAY: Any
    ITEM_BACKGROUND_COLOR: Any
    ITEM_ALT_BACKGROUND_COLOR: Any
    PUSHBUTTON_BLUE: Any
    PUSHBUTTON_BLUE_CHECKED: Any
    PUSHBUTTON_BLUE_DISABLED: Any
    TAB_PANE: Any
    SCROLLBAR_HANDLE: Any

class TextColor(Enum):
    GREEN: Any
    YELLOW: Any
    RED: Any
    WHITE: Any
    BLUE: Any
    RESET: Any
    def format(self: Any, text: str) -> str: ...

class Style(Enum):
    NORMAL: Any
    UNDERLINE: Any
    BORDER: Any
    BACKGROUND: Any
    BACKGROUND_THIN: Any

class Align(Enum):
    LEFT: Any
    RIGHT: Any
    CENTER: Any

class MessageType(Enum):
    INFO: Any
    OPERATION_COMPLETE: Any
    CONFIRM: Any
    ERROR: Any
    WARNING: Any

class PrintType(Enum):
    INFO: Any
    ERROR: Any
    WARNING: Any

class BrowserType(Enum):
    FILE: Any
    DIRECTORY: Any

class TextStyle(Enum):
    EDITABLE: Any
    READ_ONLY: Any
    UNSELECTABLE: Any

class TextType(Enum):
    PLAIN: Any
    MARKDOWN: Any
    HTML: Any

class _PyFlame(object):
    @staticmethod
    def window_resolution() -> Any: ...
    @staticmethod
    def pause(seconds: int | float = ...) -> None: ...
    @staticmethod
    def python_package_local_install(package: str | list[str]) -> bool: ...
    @staticmethod
    def cursor_busy() -> None: ...
    @staticmethod
    def cursor_restore() -> None: ...
    @staticmethod
    def print_title(text: str) -> None: ...
    @staticmethod
    def create_temp_folder(folder_name: str = ...) -> str: ...
    @staticmethod
    def cleanup_temp_folder(folder_name: str = ...) -> None: ...
    @staticmethod
    def verify_script_install(additional_files: list = ...) -> bool: ...
    @staticmethod
    def create_media_panel_libraries(library_structure: dict[str, Any]) -> None: ...
    @staticmethod
    def create_media_panel_folder(folder_name: str, folder_structure: dict[str, Any], dest: flame.PyFolder | flame.PyLibrary, shot_name_tag: str = ...) -> None: ...
    @staticmethod
    def create_media_panel_folders(folder_list: list[str], folder_structure: dict[str, Any], dest: flame.PyFolder | flame.PyLibrary) -> None: ...
    @staticmethod
    def create_file_system_folder(folder_name: str, folder_structure: dict[str, Any], dest_path: str, skip_existing: bool = ...) -> None: ...
    @staticmethod
    def create_file_system_folders(folder_list: list[str], folder_structure: dict[str, Any], dest_path: str) -> None: ...
    @staticmethod
    def copy_to_clipboard(value: str | int) -> None: ...
    @staticmethod
    def print(text: str, indent: int = ..., print_type: Any = ..., new_line: bool = ..., arrow: bool = ..., underline: bool = ..., double_underline: bool = ..., text_color: TextColor | None = ..., time: int = ..., print_to_flame: bool = ..., script_name: str = ...) -> None: ...
    @staticmethod
    def print_dict(dict_data: dict[str, Any], indent: int = ...) -> None: ...
    @staticmethod
    def print_json(json_data: Any, indent: Any = ...) -> None: ...
    @staticmethod
    def print_list(list_name: str, list_items: list, indent: Any = ..., time: int = ..., script_name: str = ...) -> None: ...
    @staticmethod
    def generate_unique_node_names(node_names: list[str], existing_node_names: list[str]) -> list[str]: ...
    @staticmethod
    def generate_unique_name(value: str, existing_names: list[str]) -> str: ...
    @staticmethod
    def get_flame_version() -> float: ...
    @staticmethod
    def get_flame_python_packages_path(print_path: bool = ...) -> str: ...
    @staticmethod
    def file_browser(path: str = ..., title: str | None = ..., extension: str | List[str] | None = ..., select_directory: bool = ..., multi_selection: bool = ..., include_resolution: bool = ..., use_flame_browser: bool = ..., window_to_hide: QtWidgets.QWidget | list[QtWidgets.QWidget] | None = ...) -> str | list | None: ...
    @staticmethod
    def open_in_finder(path: str) -> None: ...
    @staticmethod
    def raise_type_error(source_name: str | None = ..., arg_name: str | None = ..., expected_type: str | None = ..., actual_value: Any = ..., error_message: str | None = ..., time: int = ...) -> None: ...
    @staticmethod
    def raise_value_error(source_name: str = ..., arg_name: str = ..., expected_value: Any = ..., actual_value: Any = ..., error_message: str = ..., time: int = ...) -> None: ...
    @staticmethod
    def refresh_hooks(script_name: str = ...) -> None: ...
    @staticmethod
    def resolve_path_tokens(tokenized_path: str, flame_pyobject: Any = ..., date: Any = ...) -> str: ...
    @staticmethod
    def resolve_tokens(tokenized_string: str, flame_pyobject: Any = ..., date: Any = ...) -> str: ...
    @staticmethod
    def resolve_shot_name(name: str) -> str: ...
    @staticmethod
    def untar(tar_file_path: str, untar_path: str, sudo_password: str | None = ...) -> bool: ...
    @staticmethod
    def gui_resize(value: int) -> int: ...
    @staticmethod
    def font_resize(value: int) -> int: ...
    @staticmethod
    def get_export_preset_version(preset_path: str) -> Tuple[str, str]: ...
    @staticmethod
    def update_export_preset(preset_path: str) -> None: ...
    @staticmethod
    def iterate_name(existing_names: List[str], new_name: str) -> str: ...
    @staticmethod
    def get_export_preset_names() -> List[str]: ...
    @staticmethod
    def convert_export_preset_name_to_path(export_preset_name: str) -> str: ...
    @staticmethod
    def set_shot_tagging(pyobject: flame.PyLibrary | flame.PyFolder | flame.PyDesktop | flame.PyBatch | flame.PyClip, shot_name: str, append: bool = ...) -> None: ...
    @staticmethod
    def find_by_tag(pyobject: flame.PyLibrary | flame.PyDesktop | flame.PyFolder, target_tag: str, sorted: bool = ...) -> Any: ...
    @staticmethod
    def shot_name_from_clip(clip: flame.PyClip) -> str: ...
    @staticmethod
    def get_media_panel_shot_folder(shot_name: str, pyobject: flame.PyClip | flame.PyBatch | flame.PyDesktop, search_location: flame.PyLibrary | flame.PyFolder, dest_folder_path: str) -> flame.PyFolder | None: ...
    @staticmethod
    def move_to_shot_folder(shot_name: str, pyobject: flame.PyClip | flame.PyBatch | flame.PyDesktop, search_location: flame.PyLibrary | flame.PyFolder, dest_folder_path: str, expand_dest_folder: bool = ...) -> None: ...
    @staticmethod
    def copy_to_shot_folder(shot_name: str, pyobject: flame.PyClip | flame.PyBatch | flame.PyDesktop, search_location: flame.PyLibrary | flame.PyFolder, dest_folder_path: str, expand_dest_folder: bool = ...) -> None: ...

pyflame: Any
def _load_font() -> Any: ...
class PyFlameToolTip(object):
    def __init__(self: 'PyFlameToolTip', parent_widget: QtWidgets.QWidget, text: str = ..., delay: int = ..., duration: int = ...) -> None: ...
    def __del__(self: Any) -> Any: ...
    @property
    def widget(self: Any) -> QtWidgets.QWidget: ...
    @widget.setter
    def widget(self: Any, value: QtWidgets.QWidget) -> Any: ...
    @property
    def text(self: Any) -> str: ...
    @text.setter
    def text(self: Any, value: str) -> Any: ...
    @property
    def delay(self: Any) -> int: ...
    @delay.setter
    def delay(self: Any, value: int) -> Any: ...
    @property
    def duration(self: Any) -> int: ...
    @duration.setter
    def duration(self: Any, value: int) -> Any: ...
    def enter_event(self: Any) -> Any: ...
    def leave_event(self: Any) -> Any: ...
    def _show_tooltip(self: Any) -> Any: ...
    def _hide_tooltip(self: Any) -> Any: ...

class PyFlameConfig(object):
    def __init__(self: Any, config_values: Dict[str, Any], config_path: str = ..., script_name: str = ...) -> Any: ...
    def load_config(self: Any) -> None: ...
    def save_config(self: Any, config_values: Dict[str, Any] | None = ..., config_path: str | None = ...) -> None: ...
    def get_config_values(config_path: str) -> Dict[str, Any]: ...

class PyFlameButton(QtWidgets.QPushButton):
    def __init__(self: 'PyFlameButton', text: str = ..., connect: Callable[..., None] = ..., color: Color = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    @property
    def text(self: Any) -> str: ...
    @text.setter
    def text(self: Any, value: str) -> None: ...
    @property
    def color(self: Any) -> Color: ...
    @color.setter
    def color(self: Any, value: Color) -> None: ...
    @property
    def enabled(self: Any) -> bool: ...
    @enabled.setter
    def enabled(self: Any, value: bool) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    @property
    def tooltip(self: Any) -> str | None: ...
    @tooltip.setter
    def tooltip(self: Any, value: str | None) -> None: ...
    @property
    def tooltip_delay(self: Any) -> int: ...
    @tooltip_delay.setter
    def tooltip_delay(self: Any, value: int) -> None: ...
    @property
    def tooltip_duration(self: Any) -> int: ...
    @tooltip_duration.setter
    def tooltip_duration(self: Any, value: int) -> None: ...
    def connect_callback(self: Any, callback: Callable) -> None: ...
    def _set_stylesheet(self: Any, color: Color) -> None: ...
    def enterEvent(self: Any, event: Any) -> Any: ...
    def leaveEvent(self: Any, event: Any) -> Any: ...

class PyFlameEntry(QtWidgets.QLineEdit):
    def __init__(self: 'PyFlameEntry', text: str = ..., align: Align = ..., text_changed: Callable[..., None] | None = ..., placeholder_text: str = ..., read_only: bool = ..., password_echo: bool = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    @property
    def text(self: Any) -> str: ...
    @text.setter
    def text(self: Any, value: str) -> None: ...
    @property
    def align(self: Any) -> Align: ...
    @align.setter
    def align(self: Any, value: Align) -> None: ...
    @property
    def placeholder_text(self: Any) -> str | None: ...
    @placeholder_text.setter
    def placeholder_text(self: Any, value: str | None) -> None: ...
    @property
    def read_only(self: Any) -> bool: ...
    @read_only.setter
    def read_only(self: Any, value: bool) -> None: ...
    @property
    def password_echo(self: Any) -> bool: ...
    @password_echo.setter
    def password_echo(self: Any, value: bool) -> None: ...
    @property
    def enabled(self: Any) -> bool: ...
    @enabled.setter
    def enabled(self: Any, value: bool) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    @property
    def tooltip(self: Any) -> str | None: ...
    @tooltip.setter
    def tooltip(self: Any, value: str | None) -> None: ...
    @property
    def tooltip_delay(self: Any) -> int: ...
    @tooltip_delay.setter
    def tooltip_delay(self: Any, value: int) -> None: ...
    @property
    def tooltip_duration(self: Any) -> int: ...
    @tooltip_duration.setter
    def tooltip_duration(self: Any, value: int) -> None: ...
    def set_focus(self: Any) -> None: ...
    def text_changed(self: Any, connected_function: Callable) -> None: ...
    def _set_stylesheet(self: Any, read_only: Any) -> None: ...
    def mousePressEvent(self: Any, event: Any) -> Any: ...
    def mouseMoveEvent(self: Any, event: Any) -> Any: ...
    def keyPressEvent(self: Any, event: Any) -> Any: ...
    def mouseDoubleClickEvent(self: Any, event: Any) -> Any: ...
    def enterEvent(self: Any, event: Any) -> Any: ...
    def leaveEvent(self: Any, event: Any) -> Any: ...
    def eventFilter(self: Any, obj: Any, event: Any) -> Any: ...
    def _show_full_entry_text(self: Any) -> Any: ...
    def _hide_full_entry_text(self: Any) -> Any: ...

class PyFlameEntryBrowser(QtWidgets.QLineEdit):
    clicked: Any
    def __init__(self: 'PyFlameEntryBrowser', path: str, placeholder_text: str | None = ..., browser_type: BrowserType = ..., browser_ext: List[str] = ..., browser_title: str = ..., window_to_hide: list[QtWidgets.QWidget] | QtWidgets.QWidget | None = ..., connect: Callable[..., None] | None = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> Any: ...
    @property
    def path(self: Any) -> str: ...
    @path.setter
    def path(self: Any, value: str) -> None: ...
    @property
    def placeholder_text(self: Any) -> str | None: ...
    @placeholder_text.setter
    def placeholder_text(self: Any, value: str | None) -> None: ...
    @property
    def enabled(self: Any) -> bool: ...
    @enabled.setter
    def enabled(self: Any, value: bool) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    @property
    def tooltip(self: Any) -> str | None: ...
    @tooltip.setter
    def tooltip(self: Any, value: str | None) -> None: ...
    @property
    def tooltip_delay(self: Any) -> int: ...
    @tooltip_delay.setter
    def tooltip_delay(self: Any, value: int) -> None: ...
    @property
    def tooltip_duration(self: Any) -> int: ...
    @tooltip_duration.setter
    def tooltip_duration(self: Any, value: int) -> None: ...
    def connect_callback(self: Any, callback: Callable) -> None: ...
    def open_file_browser(self: Any, browser_type: BrowserType, browser_ext: list, browser_title: str, window_to_hide: list[QtWidgets.QWidget] | QtWidgets.QWidget | None = ...) -> None: ...
    def _set_stylesheet(self: Any) -> None: ...
    def mousePressEvent(self: Any, event: Any) -> Any: ...
    def mouseMoveEvent(self: Any, event: Any) -> Any: ...
    def keyPressEvent(self: Any, event: Any) -> Any: ...
    def enterEvent(self: Any, event: Any) -> Any: ...
    def leaveEvent(self: Any, event: Any) -> Any: ...

class PyFlameLabel(QtWidgets.QLabel):
    def __init__(self: 'PyFlameLabel', text: str = ..., style: Style = ..., align: Align | None = ..., underline_color: Color = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., font_size: int | None = ..., parent: QtWidgets.QWidget | None = ...) -> None: ...
    @property
    def text(self: Any) -> str: ...
    @text.setter
    def text(self: Any, value: str) -> None: ...
    @property
    def style(self: Any) -> Style: ...
    @style.setter
    def style(self: Any, value: Style) -> None: ...
    @property
    def align(self: Any) -> Align | None: ...
    @align.setter
    def align(self: Any, value: Align | None) -> None: ...
    @property
    def underline_color(self: Any) -> Color: ...
    @underline_color.setter
    def underline_color(self: Any, value: Color) -> None: ...
    @property
    def enabled(self: Any) -> bool: ...
    @enabled.setter
    def enabled(self: Any, value: bool) -> None: ...
    @property
    def width(self: Any) -> int | None: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int | None: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    @property
    def font_size(self: Any) -> int | None: ...
    @font_size.setter
    def font_size(self: Any, value: int | None) -> None: ...
    def _set_stylesheet(self: Any) -> None: ...
    def _set_underline_stylesheet(self: Any) -> None: ...

class PyFlameListWidget(QtWidgets.QListWidget):
    def __init__(self: Any, items: List[str] = ..., alternating_row_colors: bool = ..., multi_selection: bool = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    @property
    def items(self: Any) -> List[str]: ...
    @items.setter
    def items(self: Any, values: List[str]) -> None: ...
    @property
    def selected_items(self: Any) -> List[QtWidgets.QListWidgetItem]: ...
    @property
    def alternating_row_colors(self: Any) -> bool: ...
    @alternating_row_colors.setter
    def alternating_row_colors(self: Any, value: bool) -> None: ...
    @property
    def multi_selection(self: Any) -> None: ...
    @multi_selection.setter
    def multi_selection(self: Any, value: bool) -> None: ...
    @property
    def enabled(self: Any) -> bool: ...
    @enabled.setter
    def enabled(self: Any, value: bool) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    @property
    def tooltip(self: Any) -> str | None: ...
    @tooltip.setter
    def tooltip(self: Any, value: str | None) -> None: ...
    @property
    def tooltip_delay(self: Any) -> int: ...
    @tooltip_delay.setter
    def tooltip_delay(self: Any, value: int) -> None: ...
    @property
    def tooltip_duration(self: Any) -> int: ...
    @tooltip_duration.setter
    def tooltip_duration(self: Any, value: int) -> None: ...
    def add_items(self: Any, items: List[str]) -> None: ...
    def replace_items(self: Any, items: List[str]) -> None: ...
    def _set_stylesheet(self: Any) -> None: ...
    def mousePressEvent(self: Any, event: QtGui.QMouseEvent) -> None: ...
    def enterEvent(self: Any, event: Any) -> Any: ...
    def leaveEvent(self: Any, event: Any) -> Any: ...

class PyFlamePushButton(QtWidgets.QPushButton):
    def __init__(self: Any, text: str = ..., checked: bool = ..., connect: Callable[..., None] | None = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    @property
    def text(self: Any) -> str: ...
    @text.setter
    def text(self: Any, value: str) -> None: ...
    @property
    def checked(self: Any) -> bool: ...
    @checked.setter
    def checked(self: Any, value: bool) -> None: ...
    @property
    def enabled(self: Any) -> bool: ...
    @enabled.setter
    def enabled(self: Any, value: bool) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    @property
    def tooltip(self: Any) -> str | None: ...
    @tooltip.setter
    def tooltip(self: Any, value: str | None) -> None: ...
    @property
    def tooltip_delay(self: Any) -> int: ...
    @tooltip_delay.setter
    def tooltip_delay(self: Any, value: int) -> None: ...
    @property
    def tooltip_duration(self: Any) -> int: ...
    @tooltip_duration.setter
    def tooltip_duration(self: Any, value: int) -> None: ...
    def connect_callback(self: Any, callback: Callable) -> None: ...
    def _set_stylesheet(self: Any) -> None: ...
    def enterEvent(self: Any, event: Any) -> Any: ...
    def leaveEvent(self: Any, event: Any) -> Any: ...

class PyFlameMenu(QtWidgets.QPushButton):
    def __init__(self: 'PyFlameMenu', text: str = ..., align: Align = ..., menu_options: List[str] = ..., menu_indicator: bool = ..., connect: Callable[..., None] | None = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    @property
    def text(self: Any) -> str: ...
    @text.setter
    def text(self: Any, value: str) -> None: ...
    @property
    def align(self: Any) -> Align: ...
    @align.setter
    def align(self: Any, value: Align) -> None: ...
    @property
    def menu_options(self: Any) -> List[str]: ...
    @menu_options.setter
    def menu_options(self: Any, options: List[str]) -> None: ...
    @property
    def menu_indicator(self: Any) -> bool: ...
    @menu_indicator.setter
    def menu_indicator(self: Any, value: bool) -> None: ...
    @property
    def enabled(self: Any) -> bool: ...
    @enabled.setter
    def enabled(self: Any, value: bool) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    @property
    def tooltip(self: Any) -> str | None: ...
    @tooltip.setter
    def tooltip(self: Any, value: str | None) -> None: ...
    @property
    def tooltip_delay(self: Any) -> int: ...
    @tooltip_delay.setter
    def tooltip_delay(self: Any, value: int) -> None: ...
    @property
    def tooltip_duration(self: Any) -> int: ...
    @tooltip_duration.setter
    def tooltip_duration(self: Any, value: int) -> None: ...
    def update_menu(self: Any, text: str, menu_options: list[str], connect: Callable[..., None] | None = ...) -> None: ...
    def refresh_menu(self: Any) -> None: ...
    def _match_push_button_width(self: Any) -> Any: ...
    def _create_menu(self: Any, menu: Any, connect: Any) -> Any: ...
    def _set_button_stylesheet(self: Any) -> None: ...
    def _set_menu_stylesheet(self: Any) -> None: ...
    def enterEvent(self: Any, event: Any) -> Any: ...
    def leaveEvent(self: Any, event: Any) -> Any: ...

class PyFlameColorMenu(QtWidgets.QPushButton):
    def __init__(self: 'PyFlameColorMenu', color_options: Dict[str, Tuple[float, float, float, float]] = ..., color: str = ..., menu_indicator: bool = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    @property
    def color_options(self: Any) -> Dict[str, Tuple[float, float, float, float]]: ...
    @color_options.setter
    def color_options(self: Any, color_options: Dict[str, Tuple[float, float, float, float]]) -> None: ...
    @property
    def color(self: Any) -> str: ...
    @color.setter
    def color(self: Any, value: str) -> None: ...
    @property
    def color_value(self: Any) -> Tuple[float, float, float, float]: ...
    @property
    def menu_indicator(self: Any) -> bool: ...
    @menu_indicator.setter
    def menu_indicator(self: Any, value: bool) -> None: ...
    @property
    def enabled(self: Any) -> bool: ...
    @enabled.setter
    def enabled(self: Any, value: bool) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    @property
    def tooltip(self: Any) -> str | None: ...
    @tooltip.setter
    def tooltip(self: Any, value: str | None) -> None: ...
    @property
    def tooltip_delay(self: Any) -> int: ...
    @tooltip_delay.setter
    def tooltip_delay(self: Any, value: int) -> None: ...
    @property
    def tooltip_duration(self: Any) -> int: ...
    @tooltip_duration.setter
    def tooltip_duration(self: Any, value: int) -> None: ...
    def _set_color(self: Any, color: str) -> None: ...
    def _generate_color_icon(self: Any, color_value: Tuple[float, float, float, float]) -> QtGui.QIcon: ...
    def _create_menu(self: Any, color_name: Any) -> None: ...
    def _match_push_button_width(self: Any) -> Any: ...
    def _set_button_stylesheet(self: Any, menu_indicator: Any) -> None: ...
    def _set_menu_stylesheet(self: Any) -> None: ...
    def enterEvent(self: Any, event: Any) -> Any: ...
    def leaveEvent(self: Any, event: Any) -> Any: ...

class PyFlameTokenMenu(QtWidgets.QPushButton):
    def __init__(self: Any, text: str = ..., token_dict: Dict[str, str] | None = ..., token_dest: PyFlameEntry | None = ..., clear_dest: bool = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    @property
    def text(self: Any) -> str: ...
    @text.setter
    def text(self: Any, value: str) -> None: ...
    @property
    def token_dict(self: Any) -> Dict[str, str]: ...
    @token_dict.setter
    def token_dict(self: Any, value: Dict[str, str]) -> None: ...
    @property
    def token_dest(self: Any) -> Any: ...
    @token_dest.setter
    def token_dest(self: Any, value: PyFlameEntry) -> None: ...
    @property
    def clear_dest(self: Any) -> bool: ...
    @clear_dest.setter
    def clear_dest(self: Any, value: bool) -> None: ...
    @property
    def enabled(self: Any) -> bool: ...
    @enabled.setter
    def enabled(self: Any, value: bool) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    @property
    def tooltip(self: Any) -> str | None: ...
    @tooltip.setter
    def tooltip(self: Any, value: str | None) -> None: ...
    @property
    def tooltip_delay(self: Any) -> int: ...
    @tooltip_delay.setter
    def tooltip_delay(self: Any, value: int) -> None: ...
    @property
    def tooltip_duration(self: Any) -> int: ...
    @tooltip_duration.setter
    def tooltip_duration(self: Any, value: int) -> None: ...
    def add_menu_options(self: Any, new_options: Dict[str, str]) -> Any: ...
    def _build_token_menu(self: Any) -> Any: ...
    def _set_stylesheet(self: Any) -> None: ...
    def _set_menu_stylesheet(self: Any) -> Any: ...
    def enterEvent(self: Any, event: Any) -> Any: ...
    def leaveEvent(self: Any, event: Any) -> Any: ...

class PyFlameSlider(QtWidgets.QLineEdit):
    def __init__(self: 'PyFlameSlider', min_value: int = ..., max_value: int = ..., start_value: int = ..., rate: int | float = ..., connect: Callable[..., None] | None = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    @property
    def min_value(self: Any) -> int | float: ...
    @min_value.setter
    def min_value(self: Any, value: int | float) -> None: ...
    @property
    def max_value(self: Any) -> int | float: ...
    @max_value.setter
    def max_value(self: Any, value: int | float) -> None: ...
    @property
    def value(self: Any) -> int | float: ...
    @value.setter
    def value(self: Any, value: int | float) -> None: ...
    @property
    def value_str(self: Any) -> str: ...
    @property
    def rate(self: Any) -> int | float: ...
    @rate.setter
    def rate(self: Any, value: int | float) -> None: ...
    @property
    def enabled(self: Any) -> bool: ...
    @enabled.setter
    def enabled(self: Any, value: bool) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    @property
    def tooltip(self: Any) -> str | None: ...
    @tooltip.setter
    def tooltip(self: Any, value: str | None) -> None: ...
    @property
    def tooltip_delay(self: Any) -> int: ...
    @tooltip_delay.setter
    def tooltip_delay(self: Any, value: int) -> None: ...
    @property
    def tooltip_duration(self: Any) -> int: ...
    @tooltip_duration.setter
    def tooltip_duration(self: Any, value: int) -> None: ...
    def connect_callback(self: Any, callback: Callable) -> None: ...
    def _calculator(self: Any) -> Any: ...
    def _value_changed(self: Any) -> Any: ...
    def mousePressEvent(self: Any, event: Any) -> Any: ...
    def mouseReleaseEvent(self: Any, event: Any) -> Any: ...
    def mouseMoveEvent(self: Any, event: Any) -> Any: ...
    def getStepsMultiplier(self: Any, event: Any) -> Any: ...
    def setMinimum(self: Any, value: Any) -> Any: ...
    def setMaximum(self: Any, value: Any) -> Any: ...
    def setValue(self: Any, value: Any) -> Any: ...
    def _set_stylesheet(self: Any) -> None: ...
    def enterEvent(self: Any, event: Any) -> Any: ...
    def leaveEvent(self: Any, event: Any) -> Any: ...

class PyFlameTable(QtWidgets.QTableView):
    def __init__(self: 'PyFlameTable', csv_file_path: str | None = ..., alternating_row_colors: bool = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    @property
    def csv_file_path(self: Any) -> str | None: ...
    @property
    def alternating_row_colors(self: Any) -> bool: ...
    @alternating_row_colors.setter
    def alternating_row_colors(self: Any, value: bool) -> None: ...
    @property
    def enabled(self: Any) -> bool: ...
    @enabled.setter
    def enabled(self: Any, value: bool) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    @property
    def tooltip(self: Any) -> str | None: ...
    @tooltip.setter
    def tooltip(self: Any, value: str | None) -> None: ...
    @property
    def tooltip_delay(self: Any) -> int: ...
    @tooltip_delay.setter
    def tooltip_delay(self: Any, value: int) -> None: ...
    @property
    def tooltip_duration(self: Any) -> int: ...
    @tooltip_duration.setter
    def tooltip_duration(self: Any, value: int) -> None: ...
    def load_csv(self: Any, csv_file_path: str | None = ...) -> None: ...
    def save_csv_file(self: Any, csv_file_path: str) -> None: ...
    def _rename_column_header(self: Any, index: int) -> None: ...
    def _rename_selected_cells(self: Any) -> None: ...
    def _show_row_menu(self: Any, position: tuple) -> None: ...
    def _show_column_menu(self: Any, position: tuple) -> None: ...
    def _add_row(self: Any) -> None: ...
    def _delete_selected_rows(self: Any) -> None: ...
    def _add_column(self: Any) -> None: ...
    def _delete_selected_columns(self: Any) -> None: ...
    def _block_column_selection(self: Any, event: Any) -> None: ...
    def _set_stylesheet(self: Any) -> None: ...
    def _set_menu_stylesheet(self: Any) -> None: ...
    def contextMenuEvent(self: Any, event: Any) -> None: ...
    def enterEvent(self: Any, event: Any) -> Any: ...
    def leaveEvent(self: Any, event: Any) -> Any: ...

class PyFlameTabWidget(QtWidgets.QTabWidget):
    def __init__(self: Any, tab_names: list[str] = ..., grid_layout_columns: int = ..., grid_layout_rows: int = ..., grid_layout_column_width: int = ..., grid_layout_row_height: int = ..., grid_layout_adjust_column_widths: dict[int, int] = ..., grid_layout_adjust_row_heights: dict[int, int] = ..., tab_label_width: int = ..., tab_label_height: int = ..., enabled: bool = ..., parent: QtWidgets.QWidget | None = ...) -> Any: ...
    @property
    def tab_names(self: Any) -> list[str]: ...
    @tab_names.setter
    def tab_names(self: Any, value: list[str]) -> None: ...
    @property
    def grid_layout_columns(self: Any) -> int: ...
    @grid_layout_columns.setter
    def grid_layout_columns(self: Any, value: int) -> None: ...
    @property
    def grid_layout_rows(self: Any) -> int: ...
    @grid_layout_rows.setter
    def grid_layout_rows(self: Any, value: int) -> None: ...
    @property
    def grid_layout_column_width(self: Any) -> int: ...
    @grid_layout_column_width.setter
    def grid_layout_column_width(self: Any, value: int) -> None: ...
    @property
    def grid_layout_row_height(self: Any) -> int: ...
    @grid_layout_row_height.setter
    def grid_layout_row_height(self: Any, value: int) -> None: ...
    @property
    def grid_layout_adjust_column_widths(self: Any) -> dict[int, int]: ...
    @grid_layout_adjust_column_widths.setter
    def grid_layout_adjust_column_widths(self: Any, value: dict[int, int]) -> None: ...
    @property
    def grid_layout_adjust_row_heights(self: Any) -> dict[int, int]: ...
    @grid_layout_adjust_row_heights.setter
    def grid_layout_adjust_row_heights(self: Any, value: dict[int, int]) -> None: ...
    @property
    def tab_label_width(self: Any) -> int: ...
    @tab_label_width.setter
    def tab_label_width(self: Any, value: int) -> None: ...
    @property
    def tab_label_height(self: Any) -> int: ...
    @tab_label_height.setter
    def tab_label_height(self: Any, value: int) -> None: ...
    def add_tab(self: Any, name: str) -> 'PyFlameTabWidget.TabContainer': ...
    def get_current_tab_name(self: Any) -> str | None: ...
    def get_current_tab_index(self: Any) -> int: ...
    def set_current_tab(self: Any, tab: str | int) -> None: ...
    def _set_stylesheet(self: Any) -> Any: ...

class PyFlameTextEdit(QtWidgets.QTextEdit):
    def __init__(self: 'PyFlameTextEdit', text: str = ..., text_type: TextType = ..., text_style: TextStyle = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    @property
    def text_type(self: Any) -> TextType: ...
    @text_type.setter
    def text_type(self: Any, value: TextType) -> Any: ...
    @property
    def text(self: Any) -> str: ...
    @text.setter
    def text(self: Any, value: str) -> Any: ...
    @property
    def text_str(self: Any) -> str: ...
    @text_str.setter
    def text_str(self: Any, value: str) -> Any: ...
    @property
    def text_style(self: Any) -> TextStyle: ...
    @text_style.setter
    def text_style(self: Any, value: TextStyle) -> Any: ...
    @property
    def enabled(self: Any) -> bool: ...
    @enabled.setter
    def enabled(self: Any, value: bool) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    @property
    def tooltip(self: Any) -> str | None: ...
    @tooltip.setter
    def tooltip(self: Any, value: str | None) -> None: ...
    @property
    def tooltip_delay(self: Any) -> int: ...
    @tooltip_delay.setter
    def tooltip_delay(self: Any, value: int) -> None: ...
    @property
    def tooltip_duration(self: Any) -> int: ...
    @tooltip_duration.setter
    def tooltip_duration(self: Any, value: int) -> None: ...
    def _set_stylesheet(self: Any) -> Any: ...
    def enterEvent(self: Any, event: Any) -> Any: ...
    def leaveEvent(self: Any, event: Any) -> Any: ...

class PyFlameTextBrowser(QtWidgets.QTextBrowser):
    def __init__(self: 'PyFlameTextBrowser', text: str = ..., text_type: TextType = ..., text_style: TextStyle = ..., open_external_links: bool = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    @property
    def text_type(self: Any) -> TextType: ...
    @text_type.setter
    def text_type(self: Any, value: TextType) -> Any: ...
    @property
    def text(self: Any) -> str: ...
    @text.setter
    def text(self: Any, value: str) -> Any: ...
    @property
    def text_str(self: Any) -> str: ...
    @text_str.setter
    def text_str(self: Any, value: str) -> Any: ...
    @property
    def text_style(self: Any) -> TextStyle: ...
    @text_style.setter
    def text_style(self: Any, value: TextStyle) -> Any: ...
    @property
    def open_external_links(self: Any) -> bool: ...
    @open_external_links.setter
    def open_external_links(self: Any, value: bool) -> Any: ...
    @property
    def enabled(self: Any) -> bool: ...
    @enabled.setter
    def enabled(self: Any, value: bool) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    @property
    def tooltip(self: Any) -> str | None: ...
    @tooltip.setter
    def tooltip(self: Any, value: str | None) -> None: ...
    @property
    def tooltip_delay(self: Any) -> int: ...
    @tooltip_delay.setter
    def tooltip_delay(self: Any, value: int) -> None: ...
    @property
    def tooltip_duration(self: Any) -> int: ...
    @tooltip_duration.setter
    def tooltip_duration(self: Any, value: int) -> None: ...
    def _set_stylesheet(self: Any) -> Any: ...
    def enterEvent(self: Any, event: Any) -> Any: ...
    def leaveEvent(self: Any, event: Any) -> Any: ...

class PyFlameTreeWidget(QtWidgets.QTreeWidget):
    def __init__(self: 'PyFlameTreeWidget', column_names: List[str], sort: bool = ..., tree_dict: Dict[str, Dict[str, str]] = ..., tree_list: List[str] = ..., top_level_item: str | None = ..., connect: Callable[..., None] | None = ..., update_connect: Callable[..., None] | None = ..., top_level_editable: bool = ..., allow_children: bool = ..., min_items: int = ..., alternating_row_colors: bool = ..., elide_text: bool = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    @property
    def column_names(self: Any) -> List[str]: ...
    @column_names.setter
    def column_names(self: Any, value: List[str]) -> None: ...
    @property
    def sort(self: Any) -> bool: ...
    @sort.setter
    def sort(self: Any, value: bool) -> None: ...
    @property
    def tree_dict(self: Any) -> Dict[str, Dict[str, str]] | None: ...
    @tree_dict.setter
    def tree_dict(self: Any, value: Dict[str, Dict[str, str]]) -> None: ...
    @property
    def top_level_item(self: Any) -> str: ...
    @top_level_item.setter
    def top_level_item(self: Any, value: str) -> None: ...
    @property
    def tree_list(self: Any) -> List[str] | None: ...
    @tree_list.setter
    def tree_list(self: Any, value: List[str]) -> None: ...
    @property
    def tree_list_no_root(self: Any) -> List[str]: ...
    @property
    def connect_callback(self: Any) -> Callable[..., None]: ...
    @connect_callback.setter
    def connect_callback(self: Any, value: Callable[..., None]) -> None: ...
    @property
    def update_connect_callback(self: Any) -> Callable[..., None]: ...
    @update_connect_callback.setter
    def update_connect_callback(self: Any, value: Callable[..., None]) -> None: ...
    @property
    def alternating_row_colors(self: Any) -> bool: ...
    @alternating_row_colors.setter
    def alternating_row_colors(self: Any, value: bool) -> None: ...
    @property
    def allow_children(self: Any) -> bool: ...
    @allow_children.setter
    def allow_children(self: Any, value: bool) -> None: ...
    @property
    def min_items(self: Any) -> int: ...
    @min_items.setter
    def min_items(self: Any, value: int) -> None: ...
    @property
    def top_level_editable(self: Any) -> bool: ...
    @top_level_editable.setter
    def top_level_editable(self: Any, value: bool) -> None: ...
    @property
    def elide_text(self: Any) -> bool: ...
    @elide_text.setter
    def elide_text(self: Any, value: bool) -> None: ...
    @property
    def enabled(self: Any) -> bool: ...
    @enabled.setter
    def enabled(self: Any, value: bool) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    @property
    def tooltip(self: Any) -> str | None: ...
    @tooltip.setter
    def tooltip(self: Any, value: str | None) -> None: ...
    @property
    def tooltip_delay(self: Any) -> int: ...
    @tooltip_delay.setter
    def tooltip_delay(self: Any, value: int) -> None: ...
    @property
    def tooltip_duration(self: Any) -> int: ...
    @tooltip_duration.setter
    def tooltip_duration(self: Any, value: int) -> None: ...
    @property
    def all_item_paths(self: Any) -> list: ...
    @property
    def all_item_paths_no_root(self: Any) -> list: ...
    @property
    def item_path(self: Any) -> str: ...
    @property
    def item_paths(self: Any) -> List[str]: ...
    @property
    def selected_item(self: Any) -> str: ...
    def fill_tree_dict(self: Any, tree_dict: Dict[str, str], editable: bool = ...) -> None: ...
    def fill_tree_list(self: Any, tree_list: List[str]) -> None: ...
    def add_item(self: Any, item_name: str) -> None: ...
    def add_item_with_columns(self: Any, item: list[str]) -> QtWidgets.QTreeWidgetItem: ...
    def delete_item(self: Any) -> None: ...
    def sort_items(self: Any) -> None: ...
    def color_item(self: Any, item: Any, color: Any) -> None: ...
    def set_fixed_column_headers(self: Any) -> None: ...
    def clear(self: Any) -> None: ...
    def update(self: Any) -> None: ...
    def _trigger_callback(self: Any) -> None: ...
    def _on_item_collapsed(self: Any, item: Any) -> None: ...
    def _set_stylesheet(self: Any) -> None: ...
    def enterEvent(self: Any, event: Any) -> Any: ...
    def leaveEvent(self: Any, event: Any) -> Any: ...

class PyFlameProgressBarWidget(QtWidgets.QProgressBar):
    def __init__(self: 'PyFlameProgressBarWidget', total_tasks: int = ..., processing_task: int = ..., bar_color: Color = ..., bar_height: int = ..., parent: QtWidgets.QWidget | None = ...) -> None: ...
    @property
    def total_tasks(self: Any) -> int: ...
    @total_tasks.setter
    def total_tasks(self: Any, value: int) -> None: ...
    @property
    def processing_task(self: Any) -> int: ...
    @processing_task.setter
    def processing_task(self: Any, value: int) -> None: ...
    @property
    def bar_color(self: Any) -> Color: ...
    @bar_color.setter
    def bar_color(self: Any, value: Color) -> None: ...
    @property
    def bar_height(self: Any) -> int: ...
    @bar_height.setter
    def bar_height(self: Any, value: int) -> None: ...

class PyFlameButtonGroup(QtWidgets.QButtonGroup):
    def __init__(self: 'PyFlameButtonGroup', button_group: list, set_exclusive: bool = ...) -> None: ...
    @property
    def button_group(self: Any) -> list: ...
    @button_group.setter
    def button_group(self: Any, value: list) -> None: ...
    @property
    def set_exclusive(self: Any) -> bool: ...
    @set_exclusive.setter
    def set_exclusive(self: Any, value: bool) -> None: ...

class PyFlameHorizontalLine(QtWidgets.QFrame):
    def __init__(self: 'PyFlameHorizontalLine', color: Color = ..., width: int | None = ..., height: int | None = ...) -> None: ...
    @property
    def color(self: Any) -> Color: ...
    @color.setter
    def color(self: Any, value: Any) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    def _set_stylesheet(self: Any) -> None: ...

class PyFlameVerticalLine(QtWidgets.QFrame):
    def __init__(self: 'PyFlameVerticalLine', color: Color = ..., width: int | None = ..., height: int | None = ...) -> None: ...
    @property
    def color(self: Any) -> Color: ...
    @color.setter
    def color(self: Any, value: Any) -> None: ...
    @property
    def width(self: Any) -> int: ...
    @width.setter
    def width(self: Any, value: int | None) -> None: ...
    @property
    def height(self: Any) -> int: ...
    @height.setter
    def height(self: Any, value: int | None) -> None: ...
    def _set_style_sheet(self: Any) -> None: ...

class PyFlameGridLayout(QtWidgets.QGridLayout):
    def __init__(self: 'PyFlameGridLayout', columns: int = ..., rows: int = ..., column_width: int = ..., row_height: int = ..., adjust_column_widths: dict[int, int] = ..., adjust_row_heights: dict[int, int] = ...) -> None: ...

class PyFlameHBoxLayout(QtWidgets.QHBoxLayout):
    def __init__(self: 'PyFlameHBoxLayout') -> None: ...
    def setSpacing(self: Any, spacing: int) -> None: ...
    def addSpacing(self: Any, spacing: int) -> None: ...
    def setContentsMargins(self: Any, left: int, top: int, right: int, bottom: int) -> None: ...

class PyFlameVBoxLayout(QtWidgets.QVBoxLayout):
    def __init__(self: 'PyFlameVBoxLayout') -> None: ...
    def setSpacing(self: Any, spacing: int) -> None: ...
    def addSpacing(self: Any, spacing: int) -> None: ...
    def setContentsMargins(self: Any, left: int, top: int, right: int, bottom: int) -> None: ...

class PyFlameWindow(QtWidgets.QDialog):
    def __init__(self: 'PyFlameWindow', parent: QtWidgets.QWidget | None, title: str = ..., title_style: Style = ..., title_align: Align = ..., title_underline_color: Color = ..., title_height: int = ..., title_font_size: int = ..., message_bar: bool = ..., line_color: Color = ..., tab_order: list[QtWidgets.QWidget] | None = ..., return_pressed: Callable[..., None] | None = ..., escape_pressed: Callable[..., None] | None = ..., grid_layout_columns: int = ..., grid_layout_rows: int = ..., grid_layout_column_width: int = ..., grid_layout_row_height: int = ..., grid_layout_adjust_column_widths: dict[int, int] = ..., grid_layout_adjust_row_heights: dict[int, int] = ...) -> None: ...
    @property
    def line_color(self: Any) -> Color: ...
    @line_color.setter
    def line_color(self: Any, value: Color) -> None: ...
    @property
    def title(self: Any) -> str: ...
    @title.setter
    def title(self: Any, value: str) -> None: ...
    @property
    def title_style(self: Any) -> Style: ...
    @title_style.setter
    def title_style(self: Any, value: Style) -> None: ...
    @property
    def title_align(self: Any) -> Align: ...
    @title_align.setter
    def title_align(self: Any, value: Align) -> None: ...
    @property
    def title_underline_color(self: Any) -> Color: ...
    @title_underline_color.setter
    def title_underline_color(self: Any, value: Color) -> None: ...
    @property
    def title_height(self: Any) -> int: ...
    @title_height.setter
    def title_height(self: Any, value: int) -> None: ...
    @property
    def title_font_size(self: Any) -> int: ...
    @title_font_size.setter
    def title_font_size(self: Any, value: int) -> None: ...
    @property
    def message_bar_text(self: Any) -> str: ...
    @message_bar_text.setter
    def message_bar_text(self: Any, value: str) -> None: ...
    @property
    def tab_order(self: Any) -> Any: ...
    @tab_order.setter
    def tab_order(self: Any, tab_order: Any) -> Any: ...
    @property
    def return_pressed(self: Any) -> Callable[[], None] | None: ...
    @return_pressed.setter
    def return_pressed(self: Any, value: Callable[[], None] | None) -> None: ...
    @property
    def escape_pressed(self: Any) -> Callable[[], None] | None: ...
    @escape_pressed.setter
    def escape_pressed(self: Any, value: Callable[[], None] | None) -> None: ...
    @property
    def grid_layout_columns(self: Any) -> int: ...
    @grid_layout_columns.setter
    def grid_layout_columns(self: Any, value: int) -> None: ...
    @property
    def grid_layout_rows(self: Any) -> int: ...
    @grid_layout_rows.setter
    def grid_layout_rows(self: Any, value: int) -> None: ...
    @property
    def grid_layout_column_width(self: Any) -> int: ...
    @grid_layout_column_width.setter
    def grid_layout_column_width(self: Any, value: int) -> None: ...
    @property
    def grid_layout_row_height(self: Any) -> int: ...
    @grid_layout_row_height.setter
    def grid_layout_row_height(self: Any, value: int) -> None: ...
    @property
    def grid_layout_adjust_column_widths(self: Any) -> dict[int, int]: ...
    @grid_layout_adjust_column_widths.setter
    def grid_layout_adjust_column_widths(self: Any, value: dict[int, int]) -> None: ...
    @property
    def grid_layout_adjust_row_heights(self: Any) -> dict[int, int]: ...
    @grid_layout_adjust_row_heights.setter
    def grid_layout_adjust_row_heights(self: Any, value: dict[int, int]) -> None: ...
    def center_window(self: Any) -> None: ...
    def print(self: Any, message: str) -> None: ...
    def _set_stylesheet(self: Any) -> None: ...
    def mousePressEvent(self: Any, event: Any) -> Any: ...
    def mouseMoveEvent(self: Any, event: Any) -> Any: ...
    def keyPressEvent(self: Any, event: Any) -> Any: ...
    def paintEvent(self: Any, event: Any) -> Any: ...

class PyFlameInputDialog(object):
    def __init__(self: 'PyFlameInputDialog', parent: PyFlameWindow | None, text: str = ..., label_text: str = ..., title: str = ..., title_style: Style = ..., title_align: Align | None = ..., line_color: Color = ..., message_bar: bool = ...) -> Any: ...
    @property
    def text(self: Any) -> str | None: ...
    @text.setter
    def text(self: Any, value: str) -> None: ...
    @property
    def message_bar_text(self: Any) -> str: ...
    @message_bar_text.setter
    def message_bar_text(self: Any, value: str) -> None: ...
    @property
    def label_text(self: Any) -> str: ...
    @label_text.setter
    def label_text(self: Any, value: str) -> None: ...
    @property
    def title(self: Any) -> str: ...
    @title.setter
    def title(self: Any, value: str) -> None: ...
    @property
    def title_style(self: Any) -> Style: ...
    @title_style.setter
    def title_style(self: Any, value: Style) -> None: ...
    @property
    def title_align(self: Any) -> Align | None: ...
    @title_align.setter
    def title_align(self: Any, value: Align | None) -> None: ...
    @property
    def line_color(self: Any) -> Color: ...
    @line_color.setter
    def line_color(self: Any, value: Color) -> None: ...
    def _confirm(self: Any) -> None: ...
    def _cancel(self: Any) -> None: ...

class PyFlameMessageWindow(object):
    def __init__(self: 'PyFlameMessageWindow', parent: PyFlameWindow | None, message: str = ..., message_type: MessageType = ..., title: str = ..., title_style: Style = ..., title_align: Align | None = ..., line_color: Color | None = ..., message_bar: Any = ..., duration: int = ...) -> None: ...
    def __bool__(self: Any) -> Any: ...
    @property
    def message(self: Any) -> Any: ...
    @message.setter
    def message(self: Any, value: str) -> None: ...
    @property
    def message_type(self: Any) -> Any: ...
    @message_type.setter
    def message_type(self: Any, value: MessageType) -> None: ...
    @property
    def title(self: Any) -> str: ...
    @title.setter
    def title(self: Any, value: str) -> None: ...
    @property
    def title_style(self: Any) -> Style: ...
    @title_style.setter
    def title_style(self: Any, value: Style) -> None: ...
    @property
    def title_align(self: Any) -> Align: ...
    @title_align.setter
    def title_align(self: Any, value: Align | None) -> None: ...
    @property
    def line_color(self: Any) -> Color | None: ...
    @line_color.setter
    def line_color(self: Any, value: Color | None) -> None: ...
    @property
    def message_bar_text(self: Any) -> str: ...
    @message_bar_text.setter
    def message_bar_text(self: Any, value: str) -> None: ...
    @property
    def duration(self: Any) -> int: ...
    @duration.setter
    def duration(self: Any, value: int) -> None: ...
    @property
    def confirmed(self: Any) -> bool: ...
    @confirmed.setter
    def confirmed(self: Any, value: bool) -> None: ...
    def _message_print(self: Any, message: str, title: str, duration: int) -> Any: ...
    def cancel(self: Any) -> None: ...
    def confirm(self: Any) -> None: ...
    def close(self: Any) -> None: ...

class PyFlamePasswordWindow(object):
    def __init__(self: Any, parent: PyFlameWindow | None, text: str = ..., user_name_prompt: bool = ..., title: str = ..., title_style: Style = ..., title_align: Align | None = ..., line_color: Color | None = ..., message_bar: bool = ...) -> Any: ...
    @property
    def text(self: Any) -> str: ...
    @text.setter
    def text(self: Any, value: str) -> None: ...
    @property
    def title(self: Any) -> str: ...
    @title.setter
    def title(self: Any, value: str) -> None: ...
    @property
    def title_style(self: Any) -> Style: ...
    @title_style.setter
    def title_style(self: Any, value: Style) -> None: ...
    @property
    def title_align(self: Any) -> Align: ...
    @title_align.setter
    def title_align(self: Any, value: Align | None) -> None: ...
    @property
    def line_color(self: Any) -> Color | None: ...
    @line_color.setter
    def line_color(self: Any, value: Color | None) -> None: ...
    @property
    def message_bar_text(self: Any) -> str: ...
    @message_bar_text.setter
    def message_bar_text(self: Any, value: str) -> None: ...
    @property
    def password(self: Any) -> str: ...
    @password.setter
    def password(self: Any, value: str = ...) -> None: ...
    @property
    def username(self: Any) -> str: ...
    @username.setter
    def username(self: Any, value: str = ...) -> None: ...
    def _test_password(self: Any) -> Any: ...
    def _confirm(self: Any) -> Any: ...
    def _cancel(self: Any) -> Any: ...

class PyFlameProgressWindow(object):
    def __init__(self: 'PyFlameProgressWindow', parent: PyFlameWindow | None, task: str = ..., total_tasks: int = ..., task_progress_message: str = ..., title: str = ..., title_style: Style = ..., title_align: Align | None = ..., line_color: Color = ..., message_bar: bool = ...) -> None: ...
    @property
    def text(self: Any) -> str: ...
    @text.setter
    def text(self: Any, value: str) -> None: ...
    @property
    def task(self: Any) -> str: ...
    @task.setter
    def task(self: Any, value: str) -> None: ...
    @property
    def total_tasks(self: Any) -> int: ...
    @total_tasks.setter
    def total_tasks(self: Any, value: int) -> None: ...
    @property
    def current_task(self: Any) -> int: ...
    @current_task.setter
    def current_task(self: Any, value: int) -> None: ...
    @property
    def title(self: Any) -> str: ...
    @title.setter
    def title(self: Any, value: str) -> None: ...
    @property
    def title_style(self: Any) -> Style: ...
    @title_style.setter
    def title_style(self: Any, value: Style) -> None: ...
    @property
    def title_align(self: Any) -> Align: ...
    @title_align.setter
    def title_align(self: Any, value: Align | None) -> None: ...
    @property
    def line_color(self: Any) -> Color: ...
    @line_color.setter
    def line_color(self: Any, value: Color) -> None: ...
    @property
    def message_bar_text(self: Any) -> str: ...
    @message_bar_text.setter
    def message_bar_text(self: Any, value: str) -> None: ...
    def enable_done_button(self: Any) -> Any: ...
    def close(self: Any) -> Any: ...
    def text_append(self: Any, message: str) -> None: ...
    def tasks_completed(self: Any, done_button_enabled: bool = ..., task_progress_message: str = ..., title: str = ..., text_append: str = ...) -> None: ...
